application: michael-summer-tennis-2015
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.application

libraries:
- name: django
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest
